port: 3000
cacheDir: "cache"
tileSize: 256
osmBaseUrl: "https://tile.openstreetmap.org"
marker:
  radius: 8
  fillColor: "#e53935"
  borderColor: "black"
  crossColor: "white"
maxZoom: 19
minZoom: 0

# Predefined anchors for marker images (normalized 0-1 coordinates)
anchors:
  - name: center
    x: 0.5
    y: 0.5
  - name: top-left
    x: 0
    y: 0
  - name: top-center
    x: 0.5
    y: 0
  - name: top-right
    x: 1
    y: 0
  - name: bottom-left
    x: 0
    y: 1
  - name: bottom-center
    x: 0.5
    y: 1
  - name: bottom-right
    x: 1
    y: 1
  - name: left-center
    x: 0
    y: 0.5
  - name: right-center
    x: 1
    y: 0.5
  - name: bottom
    x: 0.5
    y: 1

# Custom marker images
markers:
  - name: location
    file: assets/markers/location.svg
    anchor: bottom-center
  - name: target
    file: assets/markers/target.svg
    anchor: center
  - name: star
    file: assets/markers/star.svg
    anchor: center
    fit: contain

# Defaults when query params are not provided
defaultMarker: target
defaultAnchor: center


# Tile cache configuration
cache:
  maxSize: 1000      # Maximum number of tiles to cache in memory
  ttlMinutes: 60     # Time to live for cached tiles in minutes

# CORS configuration
cors:
  enabled: true                    # Enable/disable CORS
  allowedOrigins: "*"              # Allowed origins (* for all)
  allowedMethods: "GET, OPTIONS"   # Allowed HTTP methods
  allowedHeaders: "Content-Type"   # Allowed headers
  maxAge: 86400                    # Preflight cache duration in seconds (24 hours)


attribution:
  enabled: true
  text: "© OpenStreetMap contributors"
  backgroundColor: "#000000"
  textColor: "#FFFFFF"
  opacity: 0.5